name: SonarCloud
on:
  push:
    branches:
      - release-1.2.0
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11]

    steps:
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}

    - name: Build with Maven
      run: mvn clean install
      env:
        JAVA_HOME: ${{ matrix.java-version }}

    - name: Run SonarCloud analysis
      if: matrix.java-version == 17
      run: mvn sonar:sonar
      env:
        JAVA_HOME: 17
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
